export const ORDER_ACTION_TYPES = {
  FETCH_ORDER_START: 'order/FETCH_ORDER_START',
  FETCH_ORDER_SUCCESS: 'order/FETCH_ORDER_SUCCESS',
  FETCH_ORDER_FAILED: 'order/FETCH_ORDER_FAILED',
  RESET_STATE: 'order/RESET_STATE',
};